language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: g+Pb8gbHzB8EKHMRPea7gQgadWhfAFPpEKipsk3mS37zgJ0uF8ADmrGyPQiVy/AqD1V6w/WBX5a2ysxYLXREAcU2T1kjSoxmWL0Ya55zili5VPlBQthb74AQmUM9+92UMtt5LzAq3Eil35qUOrT1Ob2nslxQMiswA65QoCPQxiDrMe3RQBcFOK9zN0/QhtVnoZzyj4j15/h4ZdhSdK0ST6d5P8RtYnLbtn+xM/BNwW8QeuZo3AJPeprOAe6FQiKjnQIhTiafSXR2LSn2Ka3BGJ5o1Xu34fEl+ZmJn0cEwDqMlXIEG6m94RmlI9FaI5C0sic+P5jR4DySpEHZNSBKsIc3OTd9hruI0+rcA9epIpEVc6Xj0t92VJaRyNwr63Uim5CECmosDzR6gnmPa5QVAKxvamtfvLH6/s35k6YSuxEXQAog2Yu2vZGb9l4kHJOZYYz5+qsDVoGV1yvJXokn0OsYaz8R+KwKqbKTLhdIaFaTC0O3saKaNrwJ5yPNbF44o1hbiyNGMsxkCqBPzh5kW5e3Gf19VeV6W5DX/2SVtBCQdkgW3YzMjpyJfCkEjY7+wfrn3kTvlDaHGEAmb4gBipD0aYKUXAkMMOE69Hih5bTnLLZeGdbkDAdqNYC6rlYMXbHLh7tDF/7qPVfbEpT5lU9zzYMdpLFftN4Gw297qo0=
  app: pure-basin-93916
  on:
    repo: maripal/treasurely-client
