language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p --dir ./build
  skip_cleanup: true
  on:
    branch: master
