language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: dJhXZd9pxIIA5wEZ7Jy7UAOavl9N+bPEspPoay2xyR2gP1nDH0056+f/KgN3dX7+8C5JilvLWwob1M3Etz0LSN0mmcpAD9tc//7gz1TnvLq+QSoI1Zw2WoP+fuM9BSzJobXCoQjx5Gp/6OobgaPSRf5YxZwN+2ZrUE1Omfc8esxhK/07WNXThkjnUi4jKDZ/o3cCsw6PSTTfCb6D78lfppbcxsfb0eXfleXrm+cZ3ptIEd8ZSBntTJLJSGdgElSofL5SbEohCsEQf1XBcUyLwN9S8794NXt1fngn7OhyyPlxaea/YlAlqDxnZiWJJLa8IG68WE4PCvAPjFf4xZQ6eCFde4Ut0fUTD4acVQ44sTOSTeXNOH+dSYK3of+GWKVlN4vWaD9ybVQuXr0ZG6FSwwCwdjOAmbiSh62e+9Mct0lNofebeerTdJcPtcy/+NKqAV84MtEmLPplvz07OabW//wx5t99YXhl44nLjKAZqKTgZFf6ilVZfzfLCDGGlFEgas9pkbPAx+GGDriV8El2uT0cEGhktxMccWlfsz4ds3xesjMSja0sInLUVEVjG+8r17XMeQ3okyXOLw093JAEay3+qA5fK7JMkiZK3MUZMm47eP5EpJAymklFFeHVbL80UvC9HhRYvQOo79ZxJ6GHA62PZAdJp96D49EnmCwnvRI=
  app: pure-basin-93916
  on:
    repo: maripal/treasurely-client
